### ISSUE TITLE
Create Web Component Package

### ISSUE THREAD

**Issue by AldoAbdn** [AldoAbdn/Escape-Room-Generator#100]
### User Story
As a developer I want to be able to download the components common to all websites (login, sign up, ect.) so that I can reuse components in other projects 

#### Estimate
8 points

#### Tasks
- [ ] Edit common web components (Login, Sign Up, Verify, ListCreator) so that they can be configured in different projects
- [ ] Create github package 
- [ ] Test the package can be referenced in other projects 

#### Acceptance Criteria
- [ ] Package is available on github
- [ ] Package can be referenced in other projects
- [ ] React components can be used in other projects

**Comment by AldoAbdn** [comment]
I've put the web components into their own directory, added a package.json file. Published it to the repo's github packages. Need to test it works in another project
