### ISSUE TITLE
Export as JSON and PDF

### ISSUE THREAD

**Issue by AldoAbdn** [AldoAbdn/Escape-Room-Generator#134]
### User Story
As a user I want to be able to download my escape room designs (json and pdf) at the same time
#### Estimate 
4 Points

#### Tasks
- [ ] Add as 'Export as JSON and PDF' option to escape rooms in dashboard
- [ ] Use SaveAs from file-saver package

#### Acceptance Criteria 
- [ ] User able to download both json and pdf as via one button/command
