### ISSUE TITLE
Export via Email

### ISSUE THREAD

**Issue by AldoAbdn** [AldoAbdn/Escape-Room-Generator#135]
### User Story
As a user I want to be able to email my escape room designs (json and pdf) to someone else

#### Estimate 
6 Points

#### Tasks
- [ ] Add an email option to escape rooms in designer
- [ ] Generate json and pdf output
- [ ] Create mailto link (might use mailtioUI library for this)
- [ ] Open mailto link

#### Acceptance Criteria 
-[ ] Users chosen mail app is opened with to, subject, content and files attached
-[ ] User is able to send the created email
