### ISSUE TITLE
Import JSON Escape Room

### ISSUE THREAD

**Issue by AldoAbdn** [AldoAbdn/Escape-Room-Generator#136]
### User Story
As a user I want to be able to import escape room designs into the app so that I can save, edit and use them

#### Estimate 
6 Points

#### Tasks
- [x] Add an import option next to the new option at the top of the dashboard
- [x] Open file picker
- [x] Save imported escape room to users list of escape rooms

#### Acceptance Criteria 
- [x] Users can pick a json file
- [x] Imported escape room is added to users list of escape room
- [x] User can open and edit imported escape room
