### ISSUE TITLE
Terms of Service

### ISSUE THREAD

**Issue by AldoAbdn** [AldoAbdn/Escape-Room-Generator#140]
### User Story
As a system administrator/app dev I want users to agree to a terms of service so that they can't use the app in an illegal way

#### Estimate 
6 Points

#### Tasks
- [ ] Add terms of service to a page in the app
- [ ] Add a checkbox to sign up so that users agree to adhere to ToS

#### Acceptance Criteria 
- [ ] ToS is available on the site/app
- [ ] A checkbox is added and must be clicked before a user can sign up
