### ISSUE TITLE
Privacy Policy

### ISSUE THREAD

**Issue by AldoAbdn** [AldoAbdn/Escape-Room-Generator#163]
### User Story
As a system administrator/app dev I want users to be able to view the privacy policy so that users know how their personal information is used/stored

#### Estimate 
6 Points

#### Tasks
- [ ] Add privacy policy to a page in the app
- [ ] Add a link to sign up so that users can view the privacy policy 

#### Acceptance Criteria 
- [ ] Privacy Policy is available on the site/app
- [ ] A link is added so that users can view the privacy policy
