### ISSUE TITLE
Required Password Strength Too Strong

### ISSUE THREAD

**Issue by AldoAbdn** [AldoAbdn/Escape-Room-Generator#97]
### User Story
As a User I want to be able to sign up for an account without having to create a super strong password 

#### Estimate
2 points

#### Task List
- [x] Lower the check on the frontend
- [x] Lower the check on the backend

#### Acceptance Criteria
- [x] When creating password for a new account, passwords of stength X are accepted 

#### Commit
42d9495047aa6ffbe3b657b10bb9ede1b03fb7b9

**Comment by AldoAbdn** [comment]
Verified that the password now accepts 'good' (level 3) passwords
